version: 0.0.{build}
image: Visual Studio 2019
build_script:
- cmd: >-
    scripts/build_imgui

    scripts/build_crossguid

    scripts/build_opengex

    scripts/build_zlib

    scripts/build_bullet

    scripts/build_cef

    scripts/build_glslangValidator

    scripts/build_spirvcross

    scripts/build

test_script:
- cmd: cmake --build build --target RUN_TESTS
